version: "3.3"

services:

  staubpfoten:
    image: php:8.1-apache
    container_name: staubpfotenc
    volumes:
      - ./dictionary/site:/var/www/html
    environment:
      - "APACHE_DOCUMENT_ROOT=var/www/html/dictionary/site"
    ports:
      - 9098:80