version: '3'

services:
  mkdocs:
    image: ghcr.io/peaceiris/mkdocs-material:v3.5.3
    container_name: staubpfotenmkdocs
    ports:
      - 8000:8000
    volumes:
      - .:/root:delegated
    stdin_open: true
    tty: true
    command:
      - "mkdocs"
      - "serve"
      - "--dev-addr=0.0.0.0:8000"
      - "--config-file"
      - "./mkdocs.yml"
