# Projektinformationen
site_name: "Staubpfoten"
site_description: "Das Rollenspiel auf dem Mars"
site_author: "hoochicken"
site_url: "http://127.0.0.1:8000"
copyright: "¬© 2026 Mareike Riegel <a href='/impressum/'>Impressum und Datenschutz</a>"

# Repository-Infos
repo_name: "GitHub"
repo_url: "https://github.com/hoochicken/staubpfoten/dictionary"
edit_uri: "dictionary/edit/main/documentation"

# Dokumentationsverzeichnis
docs_dir: "documentation"

# Theme
theme:
  name: "readthedocs"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
    - tabs

# Plugins
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - de

# Markdown-Erweiterungen
markdown_extensions:
  - markdown_include.include:  # HOE: Markdown-Dateien einf√ºgen
      base_path: documentation
  - attr_list
extra_css:
  - "assets/css/custom.css"

# Navigation
nav:
  - Startseite: index.md
  - üßë‚ÄçüöÄ Schnellstarter: rules/schnellstarter.md
